### ISSUE TITLE
Instructions unclear, leading to improper install.

### ISSUE THREAD

**Issue by Dethkiller15** [terrorist-squad/DockerChaturbateRecorderGUI#1]
Highly suggest that you do an full manual install and record the process.

I followed the instructions as closely as I could while actually being able to run all the commands and I then installed the image on my desktop first so that I could attempt a base test before I installed it on my server and even though someone is live at the time I added them it would not record them.

constantly getting these messages in the logs.

```
> ok
> 
> checkChanels
> 
> []
> 
> 1
> 
> check  cr_cr_krissone
> 
> dead  cr_cr_krissone
> 
> deletedChannels
> 
> Unable to find image 'chatrubate-recorder:latest' locally
> 
> [14/Mar/2022 19:55:13] "GET /wishlist/ HTTP/1.1" 200 206
> 
> docker: Error response from daemon: pull access denied for chatrubate-recorder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> 
> See 'docker run --help'.
> 
> [14/Mar/2022 19:55:18] "GET /wishlist/ HTTP/1.1" 200 206
> 
> ok
> 
> checkChanels
```

Any help with installing it would be helpful

**Comment by terrorist-squad** [comment]
Please run "docker build -t chatrubate-recorder ./recorder" befördert "docker-Compose -f dev.XML Update -d"

**Comment by Dethkiller15** [comment]
I did that and finally got it running properly.

ok I think a semi complete redo of the readme.md is in order...... I will go through and do that in a fork if you dont get it first.
