### ISSUE TITLE
Can't get more record

### ISSUE THREAD

**Issue by ellioat** [terrorist-squad/DockerChaturbateRecorderGUI#14]
i can't record after 1 days, how to fix. All of them is offline and my internet are fine

**Comment by terrorist-squad** [comment]
Have you changed the limits? have you already reached 20 gb?
please have a look at these settings in the compose file or post yours
```
...
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 10 #or "0" to disable this limit
...
```

**Comment by ellioat** [comment]
my docker 

> #docker-compose.yml
version: '2'

services:    
  app:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 0
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 0 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chatrubate-recorder'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - "8002:8000"
      i changed dev.yml and stable.yml but it's can't

**Comment by terrorist-squad** [comment]
The paths are already wrong "/Users/christianknedel/". Surely this is not you, because it's me? please post your compose-file

**Comment by ellioat** [comment]
services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:1.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 0 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 0 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chatrubate-recorder:1.0'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - "8002:8000" 
      
      
      
   i was able to use the record for a few hours but after  i tested it, it doesn't work anymore. i tried to change path, and recreate, stop, start and do anything but nothing happen

**Comment by ellioat** [comment]
the path u said i created in my folder.

**Comment by terrorist-squad** [comment]
Please try the following with a any channel url:
docker run -it -v /Users/CharlieScene/docker/chatrubate/input:/output cchrisknedel/chatrubate-recorder:1.0  /code/recorder.sh -u https://chaturbate.com/arikajoy/ . i need the output or a screenshot of it

**Comment by ellioat** [comment]
Unable to find image 'cchrisknedel/chatrubate-recorder:1.0' locally
docker: Error response from daemon: pull access denied for cchrisknedel/chatrubate-recorder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by terrorist-squad** [comment]
this is a copying error cchrisknedel must be chrisknedel

**Comment by ellioat** [comment]
ok bro! it's work but web ui dont' show  and the command are work :(
![image](https://user-images.githubusercontent.com/25213222/163711492-68d1329c-40a0-411b-8e03-4a3b391eb0e3.png)
![image](https://user-images.githubusercontent.com/25213222/163711495-7f8458a6-fdf7-4262-a800-2a9f594eec5b.png)

**Comment by terrorist-squad** [comment]
What shows "docker-compose -f stable.yml up" without "-d" after a while an error? I will use a logger to analyze and update the image.

**Comment by ellioat** [comment]
![image](https://user-images.githubusercontent.com/25213222/163722192-cae26324-c7f8-4857-9b8b-738a97bb12b7.png)
here

**Comment by ellioat** [comment]
![image](https://user-images.githubusercontent.com/25213222/163737683-8730c117-0183-42ff-af39-697d0219a88f.png)
here

**Comment by terrorist-squad** [comment]
Please test one of the issued docker commands and please replace the absolute path as well, otherwise no file can write and you see nothing

**Comment by ellioat** [comment]
so i delete the folder and do it again and it's work again, isn't it ?

**Comment by terrorist-squad** [comment]
Please test one of the issued docker commands and please replace the absolute path as well, otherwise no file can write and you see nothing
![163737683-8730c117-0183-42ff-af39-697d0219a88f](https://user-images.githubusercontent.com/100994062/163758868-5fc1a767-16c2-4b9f-8ed1-53347d715384.png)

**Comment by terrorist-squad** [comment]
Hi ellioat,
I have found the problem. Please try the following comose file:
`
#docker-compose.yml
version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:2.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'ShellAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /Users/christianknedel/videos:/code/database
      - /Users/christianknedel/videos:/code/videos
    ports:
      - "8002:8000"

`

**Comment by terrorist-squad** [comment]
Hi @[ellioat](https://github.com/ellioat),
i think this topic is closed
