### ISSUE TITLE
another feature request.

### ISSUE THREAD

**Issue by Dethkiller15** [terrorist-squad/DockerChaturbateRecorderGUI#15]
Add in an option in the GUI to set max quality. As some streamers stream in 4k storage can be filled quickly so being able to set it to say 720p or 1080p can be handy

**Comment by terrorist-squad** [comment]
Hi Dethkiller15 ,
the feature makes sense and will be implemented as soon as possible

**Comment by terrorist-squad** [comment]
Hi Dethkiller15 ,
I was not finished yet. but now it should work. 
* everything is in the branch https://github.com/terrorist-squad/DockerChaturbateRecorderGUI/tree/15-resolution
* you must delete the datenabnk
* rebuild the recorder image "docker build -t my-recorder recorder".
* build the application new "docker-compose -f dev_adapter_shell.yml build" and up
