### ISSUE TITLE
seems to be an issue in cron.sh

### ISSUE THREAD

**Issue by Dethkiller15** [terrorist-squad/DockerChaturbateRecorderGUI#19]
something to do with line 14 and then permissions

![image](https://user-images.githubusercontent.com/49108931/169746795-30010eca-fe61-4dab-8f15-ae7d5f87990d.png)

**Comment by Dethkiller15** [comment]
from the small amount of investigation I have done it seems that you are attempting to use "su" to log in as root. root login seems to be disabled on Ubuntu. I could be wrong

**Comment by Dethkiller15** [comment]
Also in the Dockerfile add curl to the install list it is not included by default and makes it impossible for docker to install otherwise.

**Comment by terrorist-squad** [comment]
hi, curl is already in. 
<img width="447" alt="Bildschirmfoto 2022-05-23 um 19 54 47" src="https://user-images.githubusercontent.com/100994062/169879203-f0a3ebcb-e7bd-4c99-8edf-62f7662abca3.png">


do you really live in chicago?

**Comment by terrorist-squad** [comment]
you mean the filters? ok

**Comment by Dethkiller15** [comment]
I live in the same time zone as Chicago.

ok now all that is left is the original "bash: /root/.bash_profile: Permission denied" error to fix as that also does not seem to want to run properly

I think this here may help.
https://askubuntu.com/questions/29239/where-is-bash-profile

**Comment by terrorist-squad** [comment]
i have removed the "-l".

**Comment by Dethkiller15** [comment]
While I am no longer getting errors I still can not get it to record.

I am attempting to record a model with 720p as the resolution setting.(this has been going on since before I went to the new resolution feature)

**Comment by terrorist-squad** [comment]
for myself, the shell adapter works. i am installing a new logger. Shows "ochre-compose -f ... up" without -d show an error?

**Comment by terrorist-squad** [comment]
@Dethkiller15 ,
please pull , build and start again

**Comment by Dethkiller15** [comment]
I pulled directly from docker for 2.0 version and then redid it by downloading the git from 15-res... and nada still does not work.

**Comment by Dethkiller15** [comment]
@terrorist-squad I do usually download the files and build the image however when you said "please pull" I thought you were referring to docker-pull.

**Comment by terrorist-squad** [comment]
i think i found something. please pull the git branch again .

**Comment by Dethkiller15** [comment]
it is starting the download now but that is after I found out the setting the limit to 0 did not actually disable the limit and set it to something stupidly high. 

now the only thing that is weird is that it was throwing some errors.
![image](https://user-images.githubusercontent.com/49108931/170594904-64eb7436-4ce7-4f14-a442-58a30e1e6aed.png)

**Comment by Dethkiller15** [comment]
welp one of the preformers ended their stream and I watched the recorded footage..... Yaaaaaaaa its glitchy AF. skips through the recording even though I do nothing and also even when it does play it blurs out most of the frames with weird artifacting(dont know what else to call it)

**Comment by terrorist-squad** [comment]
Hi @Dethkiller15 , I have not found the limit problem yet. But the video jump issue should be fixed now. What software do you use to play the video?

**Comment by Dethkiller15** [comment]
I use the windows 10 media player and I did try it out with VLC media player as well and had the same thing happen.

**Comment by Dethkiller15** [comment]
after testing I found out that the new transcoding fix has lead to the recording not not stop even though the performer stopped streaming.

**Comment by terrorist-squad** [comment]
hi! Streamlink is certainly great, but there is no plugin for chaturbate yet, see https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins . at livestreamer there is something, https://docs.livestreamer.io/plugin_matrix.html

i assume that the ffmpeg process terminates correctly but the status in the application is not updated.

**Comment by Dethkiller15** [comment]
> i assume that the ffmpeg process terminates correctly but the status in the application is not updated.

I can not play the video file and is also very small compared to the other video files I have captured at the same resolution for roughly the same amount of time.

**Comment by Dethkiller15** [comment]
I looked into it and as long as you give a HLS link to it, it should be able to use that to record.
https://github.com/streamlink/streamlink/blob/master/tests/mixins/stream_hls.py

**Comment by Dethkiller15** [comment]
This git here used it at the very least and is the OG version of the git I used before
https://github.com/Damianonymous/ChaturbateRecorder
