### ISSUE TITLE
Help with Setup

### ISSUE THREAD

**Issue by jamesp132** [terrorist-squad/DockerChaturbateRecorderGUI#28]
Hey, 

I have tried setting this up on my Mac, when It gets to the web server I can aa the username but it shows them as offline even though they are online and streaming. 

I'm sure this is something I'm doing wrong, please can someone help / advise where I am going wrong?

worth noting - I haven't used docker before but I've followed [DockerChaturbateRecorderGUI](https://github.com/terrorist-squad/DockerChaturbateRecorderGUI) - build from source

**Comment by terrorist-squad** [comment]
I assume you are using docker4desktop? What does "docker-compose -f stable_adapter_docker.yml up" output to you? Have you tried this "docker run -it -v /Users/CharlieScene/docker/chatrubate/input:/output chrisknedel/chaturbate-recorder' /code/recorder.sh -u https://chaturbate.com/triple_crystal/"?

**Comment by liyiecho** [comment]
if use `LIMIT_MAXIMUM_FOLDER_GB: 0` to disable this limit, but docker logs `maximum size is reached`. If want chaturbate-recorder to work , need to change the `LIMIT_MAXIMUM_FOLDER_GB` value.
