### ISSUE TITLE
$Incorrect URL!

### ISSUE THREAD

**Issue by jackadam1981** [terrorist-squad/DockerChaturbateRecorderGUI#29]
yaml:
version: '2'

services:    
  app:
    image: chrisknedel/chaturbate-recorder-gui
    container_name: recorder_app
    restart: always
    privileged: true
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chaturbate-recorder'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
    ports:
      - "8002:8000"

no recorde file.

try test:
# docker run -it -v /ChaturbateStreams/testing:/output chrisknedel/chaturbate-recorder /code/recorder.sh -u https://chaturbate.com/petitegonwild/
du: cannot access '/code/videos/': No such file or directory
$Incorrect URL!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0

see recorder log:
# docker logs -f  cr_airi
$Incorrect URL!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

some problem in URL?
i can access the website chaturbate.com  chatrubate.com
but chaturbate.com is wrong,the chaturbate.com is right.
the docker image is chrisknedel/chaturbate-recorder-gui and chrisknedel/chaturbate-recorder.
you commend is chatrubate.

out of my mind.

**Comment by jackadam1981** [comment]
I try build from source

# Copy the rest of the applicaion's code
ADD code /code
WORKDIR /code

RUN useradd -ms /bin/bash recorder

#install packages
RUN apt-get update && apt-get install -y \
ffmpeg \
curl \
cron

it must change like:
1,install packages
2,copy code

#install packages
RUN apt-get update && apt-get install -y \
ffmpeg \
curl \
cron

# Copy the rest of the applicaion's code
ADD code /code
WORKDIR /code

RUN useradd -ms /bin/bash recorder

**Comment by terrorist-squad** [comment]
Have you tried changing the Users/christianknedel/videos:/code/database folder in Docker Compose? This folder should belong to your u - and g- id in your system

**Comment by terrorist-squad** [comment]
I have now tested the following. Everything works fine
```
git clone https://github.com/terrorist-squad/DockerChaturbateRecorderGUI.git
docker build -t chatrubate-recorder ./recorder/
docker-compose -f dev_adapter_docker.yml build
docker-compose -f dev_adapter_docker.yml up
```

**Comment by terrorist-squad** [comment]
"Incorrect URL" is always there because the parameter has changed
`while getopts ":u:c:r:" o; do
    case "$o" in
        c) SLUG=${OPTARG};;
        u) URL=${OPTARG};;
        r) RESULUTION=${OPTARG};;
    esac
done


if [ -z "$url" ]
then
      echo "\$Incorrect URL!"
fi`
