### ISSUE TITLE
users offline

### ISSUE THREAD

**Issue by thecraw1** [terrorist-squad/DockerChaturbateRecorderGUI#37]
Hello. When I add a performer in the web app, the room displays as offline even if the performer is online. Thank you.

**Comment by mytrntsite** [comment]
read https://github.com/ChristianKnedel/DockerChaturbateRecorderGUI/issues/33

**Comment by thecraw1** [comment]
> read #33

Thank you very much. I will read all the issues. I'm a beginner, just installed a Debian on an i5 nuk for HA docker  ( I had HA OS for a 1-2 years on it )

**Comment by thecraw1** [comment]
> read #33

https://edge14\u002Dhel.live.mmcdn.com/live\u002Dhls/......
docker: Error response from daemon: pull access denied for chaturbate-recorder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
See 'docker run --help'.  

 I just cant make it to work . This is what I find in logs.
