### ISSUE TITLE
No longer detects channels as online

### ISSUE THREAD

**Issue by Nor882** [terrorist-squad/DockerChaturbateRecorderGUI#4]
As of this morning, channels are no longer detected as online. Attempted a new install to see if it would be fixed, but the issue is still present.

**Comment by terrorist-squad** [comment]
Maybe the limit is reached. in the dev.yml you find two values:
MAXIMUM_FOLDER_GB: 2
MAXIMUM_DOCKER_CONTAINER: 10
Please set the limits high test it again.
e.g.
`
#docker-compose.yml
version: '2'

services:    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recorder_app
    mem_limit: '256M'
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/CharlieScene/videos/"
      MAXIMUM_FOLDER_GB: 200
      MAXIMUM_DOCKER_CONTAINER: 100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/CharlieScene/videos:/code/media/videos
      - /Users/CharlieScene/videos:/code/database
    ports:
      - "8002:8000"`

**Comment by Nor882** [comment]
It turned out to be a memory issue. It worked after I allocated 60GB ram to it.

**Comment by terrorist-squad** [comment]
Holy Moly! 60gb RAM! what are you doing?

**Comment by Nor882** [comment]
I run the VM on a dedicated server, which is why there is so much ram lol. It was just recording too much at once, and the VM kept running out of memory.

**Comment by terrorist-squad** [comment]
that already sounds professional! Maybe I should include a kubernetes cluster control

**Comment by Nor882** [comment]
Ya, the VM has 12 cores assigned; I'm sure further optimization could take good advantage of them

**Comment by Nor882** [comment]
As a side note to your limit

I had to remove lines [162-166](https://github.com/terrorist-squad/DockerChaturbateRecorderGUI/blob/ab59894a0ee74c214543b5e2bcf6030bd31ee48a/interface/utils/management/commands/check_chatrubate.py#L162-L166) from [check_chatrubate.py](https://github.com/terrorist-squad/DockerChaturbateRecorderGUI/commit/6f1d7775013ac111c1bbe6249861ade45bc3a2f2) because it does not play well with network drives.
