### ISSUE TITLE
unable to record in GUI

### ISSUE THREAD

**Issue by meddle99** [terrorist-squad/DockerChaturbateRecorderGUI#5]
I followed the instructions, but I can't get the GUI to work.   When I try to record using the command line as shown in step 1, it records fine.  However, when I add a channel to the GUI as shown in the HOWTO section, the GUI constantly says the channel is offline.

Also, is there a way to record using a user other than root?

**Comment by terrorist-squad** [comment]
Bitte versuche einmal folgendes mit einer bilibigen Channel-url:
docker run -it -v /Users/CharlieScene/docker/chatrubate/input:/output chrisknedel/chatrubate-recorder /code/recorder.sh -u https://chaturbate.com/arikajoy/

Wichtig ist, dass hinter dem channel namen nichts folgt, zum beispiel: /code/recorder.sh -u https://chaturbate.com/arikajoy/?page=2 . Die Gui sollte das bereits wegfiltern.

Hast du einen Proxy oder so etwas ?

**Comment by terrorist-squad** [comment]
Please try the following with a bilib channel url:
docker run -it -v /Users/CharlieScene/docker/chatrubate/input:/output chrisknedel/chatrubate-recorder /code/recorder.sh -u https://chaturbate.com/arikajoy/

It is important that the channel name is not followed by anything, for example: /code/recorder.sh -u https://chaturbate.com/arikajoy/?page=2 . The gui should already filter this out.

Do you have a proxy or something ?

**Comment by terrorist-squad** [comment]
I have opened a branch for the rootless feature: https://github.com/terrorist-squad/DockerChaturbateRecorderGUI/tree/%235-rootless-feature

**Comment by meddle99** [comment]
> Please try the following with a any channel url: `docker run -it -v /Users/CharlieScene/docker/chatrubate/input:/output chrisknedel/chatrubate-recorder /code/recorder.sh -u https://chaturbate.com/arikajoy/`
> 

this works at the command line and the GUI now when i use the pre-compiled image.  I see the changes you made in the dockerfile.   That was what i was going to do, once i got a successful compile on my own.  I am still learning docker, so i'll try again.

thanks
